name: Codiumate Setup

on:
  push:
    branches:
      - main

jobs:
  codiumate_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Codiumate
        uses: codium-ai/codiumate@latest
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
